#!/usr/bin/env python3
"""Sync pipeline metadata into the Obsidian wiki and sentinel-marked doc tables.

One script, one direction: code/DB -> .gen.md files and sentinel tables.

Usage:
    python scripts/sync_wiki.py sync      # generate all .gen.md + update doc tables
    python scripts/sync_wiki.py lint      # check .gen.md not hand-edited, stale .suggest.md

The script reads from:
  - sc_tools.pipeline.STANDARD_PHASES (canonical phase metadata)
  - sc_tools.registry (project_phases table, if available)

And writes to:
  - docs/wiki/sc_tools/phases.gen.md
  - docs/wiki/sc_tools/checkpoints.gen.md
  - docs/wiki/sc_tools/changelog.gen.md
  - docs/wiki/projects/{name}/status.gen.md  (per project)
  - README.md, CLAUDE.md, Architecture.md (sentinel-marked tables)
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Repo root is two levels up from scripts/
REPO_ROOT = Path(__file__).resolve().parent.parent
WIKI_ROOT = REPO_ROOT / "docs" / "wiki"


# ---------------------------------------------------------------------------
# Phase table generation from pipeline.py
# ---------------------------------------------------------------------------


def _get_phases() -> dict:
    """Import STANDARD_PHASES from sc_tools.pipeline."""
    sys.path.insert(0, str(REPO_ROOT))
    from sc_tools.pipeline import STANDARD_PHASES

    return STANDARD_PHASES


def generate_phases_md(phases: dict) -> str:
    """Generate docs/wiki/sc_tools/phases.gen.md from PhaseSpec data."""
    fm = _frontmatter(
        {
            "type": "phases",
            "tier": "tool-design",
            "cssclasses": ["generated"],
            "generated": True,
        }
    )
    lines = [
        fm,
        "",
        "# Pipeline Phases",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: `sc_tools/pipeline.py`. Do not edit manually.",
        "",
        "| Slug | Name | Old Code | Branch | Checkpoint | Optional | HIL | Iterative |",
        "|------|------|----------|--------|------------|----------|-----|-----------|",
    ]
    for slug, spec in phases.items():
        cp = f"`{spec.checkpoint}`" if spec.checkpoint else "-"
        opt = "yes" if spec.optional else ""
        hil = "yes" if spec.human_in_loop else ""
        it = "yes" if spec.iterative else ""
        lines.append(
            f"| `{slug}` | {spec.label} | {spec.old_code} | {spec.branch} | {cp} | {opt} | {hil} | {it} |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_checkpoints_md(phases: dict) -> str:
    """Generate docs/wiki/sc_tools/checkpoints.gen.md with required metadata per phase."""
    fm = _frontmatter(
        {
            "type": "checkpoints",
            "tier": "tool-design",
            "cssclasses": ["generated"],
            "generated": True,
        }
    )
    lines = [
        fm,
        "",
        "# Checkpoint Contracts",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: `sc_tools/pipeline.py`. Do not edit manually.",
        "",
    ]
    for slug, spec in phases.items():
        cp = f"`{spec.checkpoint}`" if spec.checkpoint else "*(no checkpoint)*"
        lines.append(f"## {slug}")
        lines.append("")
        lines.append(f"**Label:** {spec.label}  ")
        lines.append(f"**Checkpoint:** {cp}  ")
        if spec.required_obs:
            obs_str = ", ".join(f"`{o}`" for o in spec.required_obs)
            lines.append(f"**Required obs:** {obs_str}  ")
        if spec.required_obsm:
            obsm_str = ", ".join(f"`{o}`" for o in spec.required_obsm)
            lines.append(f"**Required obsm:** {obsm_str}  ")
        if spec.x_format:
            lines.append(f"**X format:** {spec.x_format}  ")
        if spec.qc_report:
            lines.append(f"**QC report:** `{spec.qc_report}`  ")
        lines.append("")
    return "\n".join(lines)


def _frontmatter(props: dict) -> str:
    """Build YAML frontmatter block from a dict of properties."""
    lines = ["---"]
    for k, v in props.items():
        if isinstance(v, list):
            lines.append(f"{k}:")
            for item in v:
                lines.append(f"  - {item}")
        elif isinstance(v, bool):
            lines.append(f"{k}: {'true' if v else 'false'}")
        else:
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines)


def generate_changelog_md() -> str:
    """Generate docs/wiki/sc_tools/changelog.gen.md from registry phase transitions."""
    fm = _frontmatter(
        {
            "type": "changelog",
            "tier": "tool-design",
            "cssclasses": ["generated"],
            "generated": True,
        }
    )
    lines = [
        fm,
        "",
        "# Phase Changelog",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: registry database. Do not edit manually.",
        "",
    ]
    try:
        from sc_tools.registry import Registry

        reg = Registry()
        # Collect all phases across all projects, sort by updated_at desc
        all_entries: list[tuple[str, dict]] = []
        for proj in reg.list_projects():
            proj_name = proj["name"]
            for phase in reg.list_phases(proj_name):
                all_entries.append((proj_name, phase))
        all_entries.sort(key=lambda x: x[1].get("updated_at", ""), reverse=True)
        entries = all_entries[:50]
        if entries:
            lines.append("| Date | Project | Phase | Status |")
            lines.append("|------|---------|-------|--------|")
            for proj_name, phase in entries:
                date_str = str(phase.get("updated_at", ""))[:10] or "?"
                lines.append(
                    f"| {date_str} | {proj_name} | `{phase['phase']}` | {phase['status']} |"
                )
        else:
            lines.append("*No phase transitions recorded yet.*")
    except Exception:
        lines.append("*Registry not available. Run `pip install sc-tools[registry]` to enable.*")
    lines.append("")
    return "\n".join(lines)


def generate_project_status_md(project_name: str) -> str:
    """Generate docs/wiki/projects/{name}/status.gen.md from registry."""
    # Collect phase data for frontmatter
    fm_props: dict = {
        "type": "status",
        "project": project_name,
        "tier": "project",
        "cssclasses": ["generated"],
        "generated": True,
    }

    phases_data: list[dict] = []
    try:
        from sc_tools.registry import Registry

        reg = Registry()
        phases_data = reg.list_phases(project_name)

        # Compute summary stats for frontmatter
        if phases_data:
            complete = sum(1 for p in phases_data if p["status"] == "complete")
            total = len(phases_data)
            fm_props["phases_complete"] = complete
            fm_props["phases_total"] = total

            # Find the furthest active phase
            in_progress = [p for p in phases_data if p["status"] == "in_progress"]
            if in_progress:
                fm_props["current_phase"] = in_progress[-1]["phase"]
            elif complete > 0:
                fm_props["current_phase"] = phases_data[-1]["phase"]

        # Try to get platform from project record
        try:
            proj = reg.get_project(project_name)
            if proj and proj.get("imaging_modality"):
                fm_props["platform"] = proj["imaging_modality"]
        except Exception:
            pass
    except Exception:
        pass

    fm = _frontmatter(fm_props)
    lines = [
        fm,
        "",
        f"# {project_name} — Pipeline Status",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: registry database. Do not edit manually.",
        "",
    ]

    if phases_data:
        lines.append("| Phase | Status | n_obs | n_vars | n_samples | Updated | Notes |")
        lines.append("|-------|--------|-------|--------|-----------|---------|-------|")
        for p in phases_data:
            date_str = str(p.get("updated_at", ""))[:10] or ""
            notes = p.get("notes") or ""
            n_obs = f"{p['n_obs']:,}" if p.get("n_obs") else ""
            n_vars = f"{p['n_vars']:,}" if p.get("n_vars") else ""
            n_samples = str(p["n_samples"]) if p.get("n_samples") else ""
            lines.append(
                f"| `{p['phase']}` | {p['status']} | {n_obs} | {n_vars} | {n_samples} | {date_str} | {notes} |"
            )
    else:
        lines.append("*No phase data recorded. Use `set_phase_status` MCP tool or registry API.*")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Sentinel table replacement in doc files
# ---------------------------------------------------------------------------


def _build_phase_table(phases: dict) -> str:
    """Build the markdown phase table used in README, CLAUDE.md, Architecture.md."""
    lines = [
        "| Slug | Old code | Name | Checkpoint | Required Data | QC Report |",
        "|------|----------|------|------------|---------------|-----------|",
    ]
    for slug, spec in phases.items():
        cp = f"`{spec.checkpoint}`" if spec.checkpoint else "-"
        # Build required data summary
        parts = []
        if spec.required_obs:
            parts.append(f"`obs[{', '.join(spec.required_obs)}]`")
        if spec.required_obsm:
            parts.append(f"`obsm[{', '.join(spec.required_obsm)}]`")
        if spec.x_format:
            parts.append(f"`X` {spec.x_format}")
        req = ", ".join(parts) if parts else "-"
        qc = f"`{spec.qc_report}`" if spec.qc_report else ""
        lines.append(f"| `{slug}` | {spec.old_code} | {spec.label} | {cp} | {req} | {qc} |")
    return "\n".join(lines)


SENTINEL_PATTERN = re.compile(
    r"(<!-- PHASE_TABLE:START -->)\n.*?\n(<!-- PHASE_TABLE:END -->)",
    re.DOTALL,
)

PROJECT_TABLE_PATTERN = re.compile(
    r"(<!-- PROJECT_TABLE:START -->)\n.*?\n(<!-- PROJECT_TABLE:END -->)",
    re.DOTALL,
)

ACTIVE_PLANS_PATTERN = re.compile(
    r"(<!-- ACTIVE_PLANS:START -->)\n.*?\n(<!-- ACTIVE_PLANS:END -->)",
    re.DOTALL,
)


def update_sentinel_file(filepath: Path, table: str) -> bool:
    """Replace content between PHASE_TABLE sentinels. Returns True if changed."""
    if not filepath.exists():
        return False
    content = filepath.read_text()
    if "<!-- PHASE_TABLE:START -->" not in content:
        return False
    replacement = f"<!-- PHASE_TABLE:START -->\n\n{table}\n\n<!-- PHASE_TABLE:END -->"
    new_content = SENTINEL_PATTERN.sub(replacement, content)
    if new_content == content:
        return False
    filepath.write_text(new_content)
    return True


_PLATFORM_LABELS: dict[str, str] = {
    "sequencing_based": "Visium",
    "mass_spec_imaging": "IMC",
    "probe_based": "CosMx",
    "multiplatform": "Multi",
}

# Projects with wiki pages (have Mission.md, Journal.md, hypotheses.md links)
_WIKI_PROJECTS: dict[str, str] = {
    "ggo_visium": "[[ggo_visium/Mission\\|Mission]] · [[ggo_visium/hypotheses\\|Hyp]] · [[ggo_visium/Journal\\|Journal]]",
    "robin": "[[robin/Mission\\|Mission]] · [[robin/hypotheses\\|Hyp]] · [[robin/Journal\\|Journal]]",
    "lymph_dlbcl": "[[lymph_dlbcl/Mission\\|Mission]] · [[lymph_dlbcl/hypotheses\\|Hyp]] · [[lymph_dlbcl/Journal\\|Journal]]",
    "ggo_human": "[[ggo_human/hypotheses\\|Hyp]] · [[ggo_human/journal\\|Journal]]",
    "ibd_spatial": "[[ibd_spatial/Mission\\|Mission]] · [[ibd_spatial/hypotheses\\|Hyp]] · [[ibd_spatial/Journal\\|Journal]]",
    "robin_cell": "[[robin/Mission\\|Mission]]",
}


def _build_project_table() -> str:
    """Build a markdown project summary table from registry data.

    Wiki projects (those with Mission/Journal/hypotheses pages) go in the main
    table with links.  Extra registry-only projects are listed in a collapsed
    details block underneath.
    """

    def _friendly_platform(proj: dict) -> str:
        raw = proj.get("imaging_modality") or proj.get("domain") or ""
        return _PLATFORM_LABELS.get(raw, raw)

    def _phase_summary(phases: list[dict]) -> tuple[str, str, str, str, str]:
        complete = sum(1 for p in phases if p["status"] == "complete")
        total = len(phases)
        progress = f"{complete}/{total}" if total else "0/0"
        current = ""
        in_prog = [p for p in phases if p["status"] == "in_progress"]
        if in_prog:
            current = in_prog[-1]["phase"]
        elif phases:
            done = [p for p in phases if p["status"] == "complete"]
            if done:
                current = done[-1]["phase"]
        n_obs = n_vars = n_samples = ""
        for p in reversed(phases):
            if p.get("n_obs"):
                n_obs = f"{p['n_obs']:,}"
                break
        for p in reversed(phases):
            if p.get("n_vars"):
                n_vars = f"{p['n_vars']:,}"
                break
        for p in reversed(phases):
            if p.get("n_samples"):
                n_samples = str(p["n_samples"])
                break
        return current, n_obs, n_vars, n_samples, progress

    main_lines = [
        "| Project | Platform | Current Phase | n_obs | n_vars | Progress | Links |",
        "|---------|----------|---------------|-------|--------|----------|-------|",
    ]
    extra_lines = [
        "| Project | Platform | Current Phase | Progress |",
        "|---------|----------|---------------|----------|",
    ]
    try:
        from sc_tools.registry import Registry

        reg = Registry()
        for proj in reg.list_projects():
            name = proj["name"]
            platform = _friendly_platform(proj)
            phases = reg.list_phases(name)
            current, n_obs, n_vars, n_samples, progress = _phase_summary(phases)

            if name in _WIKI_PROJECTS:
                links = _WIKI_PROJECTS[name]
                main_lines.append(
                    f"| **{name}** | {platform} | {current} | {n_obs} | {n_vars} | {progress} | {links} |"
                )
            else:
                extra_lines.append(f"| {name} | {platform} | {current} | {progress} |")
    except Exception:
        main_lines.append("| *(registry unavailable)* | | | | | | |")

    parts = ["\n".join(main_lines)]
    if len(extra_lines) > 2:  # more than just header + separator
        parts.append("")
        # Use Obsidian callout (foldable) instead of <details> for rendering
        parts.append("> [!info]- Registry-only projects (no wiki pages)")
        for line in extra_lines:
            parts.append(f"> {line}")
    return "\n".join(parts)


def update_project_table_file(filepath: Path, table: str) -> bool:
    """Replace content between PROJECT_TABLE sentinels. Returns True if changed."""
    if not filepath.exists():
        return False
    content = filepath.read_text()
    if "<!-- PROJECT_TABLE:START -->" not in content:
        return False
    replacement = f"<!-- PROJECT_TABLE:START -->\n\n{table}\n\n<!-- PROJECT_TABLE:END -->"
    new_content = PROJECT_TABLE_PATTERN.sub(replacement, content)
    if new_content == content:
        return False
    filepath.write_text(new_content)
    return True


# ---------------------------------------------------------------------------
# Active plans table from docs/wiki/plans/
# ---------------------------------------------------------------------------


def _parse_frontmatter(content: str) -> dict[str, str]:
    """Parse simple YAML frontmatter (key: value pairs) into a dict."""
    props: dict[str, str] = {}
    lines = content.splitlines()
    if not lines or lines[0].strip() != "---":
        return props
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            key, _, val = line.partition(":")
            props[key.strip()] = val.strip().strip('"').strip("'")
    return props


def _build_active_plans_table(plans_dir: Path | None = None) -> str:
    """Build a markdown table of active/in_progress plans from docs/wiki/plans/.

    Scans tier1/, tier2/, untiered/, and the plans root (legacy flat files).

    Parameters
    ----------
    plans_dir:
        Override for the plans directory (used in tests).
    """
    if plans_dir is None:
        plans_dir = WIKI_ROOT / "plans"

    if not plans_dir.exists():
        return "*No active plans*"

    active_statuses = {"active", "in_progress"}
    rows: list[tuple[str, str, str, str, str]] = []  # (date, slug, title, status, tier)

    # Scan root (legacy/flat) + tier subdirs
    scan_dirs = [
        (plans_dir, "untiered"),
        (plans_dir / "tier1", "tier1"),
        (plans_dir / "tier2", "tier2"),
        (plans_dir / "untiered", "untiered"),
    ]
    seen: set[str] = set()
    for scan_dir, _tier_label in scan_dirs:
        if not scan_dir.exists():
            continue
        for plan_file in sorted(scan_dir.glob("*.md")):
            if plan_file.name.startswith(".") or plan_file.stem in seen:
                continue
            # Skip _index files
            if plan_file.stem.startswith("_"):
                continue
            seen.add(plan_file.stem)
            content = plan_file.read_text()
            fm = _parse_frontmatter(content)
            status = fm.get("status", "active")
            if status not in active_statuses:
                continue
            title = fm.get("summary", "") or ""
            for line in content.splitlines():
                if line.strip().startswith("# "):
                    title = line.strip()[2:].strip()
                    break
            created = fm.get("created", "")
            slug = plan_file.stem
            # Determine link prefix relative to plans/
            rel = plan_file.relative_to(plans_dir).parent
            link_prefix = str(rel) if str(rel) != "." else ""
            rows.append((created, slug, title, status, link_prefix))

    if not rows:
        return "*No active plans*"

    lines = [
        "| Plan | Tier | Date | Status |",
        "|------|------|------|--------|",
    ]
    for created, slug, title, status, link_prefix in rows:
        path = f"plans/{link_prefix}/{slug}" if link_prefix else f"plans/{slug}"
        link = f"[[{path}|{title}]]"
        tier_label = link_prefix if link_prefix else "untiered"
        lines.append(f"| {link} | {tier_label} | {created} | {status} |")
    return "\n".join(lines)


def update_active_plans_file(filepath: Path, table: str) -> bool:
    """Replace content between ACTIVE_PLANS sentinels. Returns True if changed."""
    if not filepath.exists():
        return False
    content = filepath.read_text()
    if "<!-- ACTIVE_PLANS:START -->" not in content:
        return False
    replacement = f"<!-- ACTIVE_PLANS:START -->\n\n{table}\n\n<!-- ACTIVE_PLANS:END -->"
    new_content = ACTIVE_PLANS_PATTERN.sub(replacement, content)
    if new_content == content:
        return False
    filepath.write_text(new_content)
    return True


# ---------------------------------------------------------------------------
# Nexus dashboard
# ---------------------------------------------------------------------------


def _build_next_phases_table() -> str:
    """Build a table of available next phases per project using the pipeline DAG."""
    lines = [
        "| Project | Can Start Next |",
        "|---------|----------------|",
    ]
    try:
        from sc_tools.pipeline import get_available_next
        from sc_tools.registry import Registry

        reg = Registry()
        any_rows = False
        for proj in reg.list_projects():
            name = proj["name"]
            phases = reg.list_phases(name)
            completed = {p["phase"] for p in phases if p["status"] == "complete"}
            available = get_available_next(completed)
            if available:
                next_str = ", ".join(f"`{s}`" for s in available)
                lines.append(f"| {name} | {next_str} |")
                any_rows = True
        if not any_rows:
            return "*No project phase data recorded.*"
    except Exception:
        return "*Registry not available.*"
    return "\n".join(lines)


def generate_nexus_md(phases: dict, plans_dir: Path | None = None) -> str:
    """Generate docs/wiki/sc_tools/nexus.gen.md — flat ecosystem state for Claude Code.

    Parameters
    ----------
    phases:
        STANDARD_PHASES dict from sc_tools.pipeline.
    plans_dir:
        Override for plans directory (used in tests).
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    fm = _frontmatter(
        {
            "type": "nexus",
            "tier": "tool-design",
            "cssclasses": ["generated"],
            "generated": True,
            "updated": now,
        }
    )

    # Section 1: All projects (flat — no Obsidian transclusion)
    project_table = _build_project_table()

    # Section 2: Available next phases
    next_phases = _build_next_phases_table()

    # Section 3: Active plans (reuse existing builder)
    active_plans = _build_active_plans_table(plans_dir=plans_dir)

    # Section 4: BioData summary
    biodata_summary = _build_biodata_summary()

    # Section 5: Recent phase transitions (last 10)
    recent_transitions = _build_recent_transitions(limit=10)

    key_docs = (
        "| Doc | Path | Purpose |\n"
        "|-----|------|---------|\n"
        "| Architecture | `docs/Architecture.md` | Pipeline phases, checkpoints, data flow |\n"
        "| Registry | `docs/registry.md` | Storage layer, schema, BioData, MCP servers |\n"
        "| Mission | `docs/Mission.md` | Toolkit-level todo list and roadmap |\n"
        "| Journal | `docs/Journal.md` | Toolkit-level decision log |\n"
        "| Skills | `docs/skills.md` | Coding and analysis standards |\n"
        "| BioData hierarchy | `docs/wiki/knowledge/biodata-hierarchy.md` | Platform taxonomy |\n"
        "| Clinical schema | `docs/wiki/knowledge/clinical-data-schema.md` | Subject/cohort fields |\n"
        "| Plans | `docs/wiki/plans/` | tier1 (architectural), tier2 (sub-task), untiered (auto-save) |"
    )

    lines = [
        fm,
        "",
        "# sc_tools Nexus — Ecosystem State",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Do not edit manually. Last updated: " + now,
        "",
        "---",
        "",
        "## Key Docs",
        "",
        key_docs,
        "",
        "---",
        "",
        "## All Projects",
        "",
        project_table,
        "",
        "---",
        "",
        "## Available Next Phases",
        "",
        next_phases,
        "",
        "---",
        "",
        "## Active Plans",
        "",
        active_plans,
        "",
        "---",
        "",
        "## BioData Registry",
        "",
        biodata_summary,
        "",
        "---",
        "",
        "## Recent Phase Transitions",
        "",
        recent_transitions,
        "",
    ]
    return "\n".join(lines)


def _build_biodata_summary() -> str:
    """Return a markdown summary of BioData, Subject, and Sample counts."""
    try:
        from sc_tools.registry import Registry

        reg = Registry()
        s = reg.status()
        n_subjects = s.get("n_subjects", 0)
        n_samples = s.get("n_samples", 0)
        n_biodata = s.get("n_biodata", 0)
        n_datasets = s.get("n_datasets", 0)

        lines = [
            f"**Totals:** {n_subjects} subjects, {n_samples} samples, "
            f"{n_biodata} BioData objects, {n_datasets} legacy datasets",
            "",
            "| Project | BioData Type | Modality | Count |",
            "|---------|-------------|----------|-------|",
        ]
        for proj in reg.list_projects():
            summary = reg.project_data_summary(proj["name"])
            if summary["total"] > 0:
                for cat, count in sorted(summary["by_category"].items()):
                    # Find the dominant modality for this category
                    mod_str = ""
                    by_mod = summary.get("by_modality", {})
                    if by_mod:
                        mod_str = ", ".join(m for m in sorted(by_mod.keys()) if m != "unknown")
                    lines.append(f"| {proj['name']} | {cat} | {mod_str} | {count} |")
        if len(lines) == 4:  # only header
            lines.append("| *(no BioData registered)* | | | |")
        return "\n".join(lines)
    except Exception:
        return "*Registry not available for BioData summary.*"


def _build_recent_transitions(limit: int = 10) -> str:
    """Return a markdown table of the most recent phase transitions."""
    try:
        from sc_tools.registry import Registry

        reg = Registry()
        all_entries: list[tuple[str, dict]] = []
        for proj in reg.list_projects():
            proj_name = proj["name"]
            for phase in reg.list_phases(proj_name):
                all_entries.append((proj_name, phase))
        all_entries.sort(key=lambda x: x[1].get("updated_at", ""), reverse=True)
        entries = all_entries[:limit]
        if not entries:
            return "*No phase transitions recorded yet.*"
        lines = [
            "| Date | Project | Phase | Status |",
            "|------|---------|-------|--------|",
        ]
        for proj_name, phase in entries:
            date_str = str(phase.get("updated_at", ""))[:10] or "?"
            lines.append(f"| {date_str} | {proj_name} | `{phase['phase']}` | {phase['status']} |")
        return "\n".join(lines)
    except Exception:
        return "*Registry not available.*"


# ---------------------------------------------------------------------------
# Discover projects
# ---------------------------------------------------------------------------


def discover_projects() -> list[str]:
    """Find project names from docs/wiki/projects/ or projects/ directory."""
    wiki_projects = WIKI_ROOT / "projects"
    if wiki_projects.exists():
        return [
            d.name
            for d in sorted(wiki_projects.iterdir())
            if d.is_dir() and not d.name.startswith(".")
        ]
    # Fallback: scan projects/ for directories with Mission.md or Journal.md
    projects_root = REPO_ROOT / "projects"
    names = []
    for platform_dir in sorted(projects_root.iterdir()):
        if not platform_dir.is_dir() or platform_dir.name.startswith("."):
            continue
        for proj_dir in sorted(platform_dir.iterdir()):
            if proj_dir.is_dir() and (
                (proj_dir / "Journal.md").exists() or (proj_dir / "Snakefile").exists()
            ):
                names.append(proj_dir.name)
    return names


# ---------------------------------------------------------------------------
# sync subcommand
# ---------------------------------------------------------------------------


def cmd_sync() -> None:
    """Generate all .gen.md files and update sentinel tables."""
    phases = _get_phases()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # 1. Wiki .gen.md files
    sc_dir = WIKI_ROOT / "sc_tools"
    sc_dir.mkdir(parents=True, exist_ok=True)

    (sc_dir / "phases.gen.md").write_text(generate_phases_md(phases))
    print(f"  wrote {sc_dir / 'phases.gen.md'}")

    (sc_dir / "checkpoints.gen.md").write_text(generate_checkpoints_md(phases))
    print(f"  wrote {sc_dir / 'checkpoints.gen.md'}")

    (sc_dir / "changelog.gen.md").write_text(generate_changelog_md())
    print(f"  wrote {sc_dir / 'changelog.gen.md'}")

    # 2. Per-project status.gen.md
    projects = discover_projects()
    for name in projects:
        proj_dir = WIKI_ROOT / "projects" / name
        proj_dir.mkdir(parents=True, exist_ok=True)
        (proj_dir / "status.gen.md").write_text(generate_project_status_md(name))
        print(f"  wrote {proj_dir / 'status.gen.md'}")

    # 3. Sentinel tables in doc files
    table = _build_phase_table(phases)
    for doc in ["README.md", "CLAUDE.md", "docs/Architecture.md"]:
        filepath = REPO_ROOT / doc
        if update_sentinel_file(filepath, table):
            print(f"  updated sentinel in {doc}")
        else:
            if filepath.exists() and "<!-- PHASE_TABLE:START -->" not in filepath.read_text():
                print(f"  skip {doc} (no sentinels yet)")

    # 4. Project table in index.md
    project_table = _build_project_table()
    index_path = WIKI_ROOT / "index.md"
    if update_project_table_file(index_path, project_table):
        print("  updated PROJECT_TABLE in index.md")

    # 5. Active plans table in Mission.md
    active_plans_table = _build_active_plans_table()
    mission_path = REPO_ROOT / "docs" / "Mission.md"
    if update_active_plans_file(mission_path, active_plans_table):
        print("  updated ACTIVE_PLANS in Mission.md")

    # 6. Nexus dashboard (flat ecosystem state for Claude Code)
    nexus_md = generate_nexus_md(phases)
    (sc_dir / "nexus.gen.md").write_text(nexus_md)
    print(f"  wrote {sc_dir / 'nexus.gen.md'}")

    print(f"\nwiki-sync complete at {now}")


# ---------------------------------------------------------------------------
# lint subcommand
# ---------------------------------------------------------------------------


def cmd_lint() -> None:
    """Check .gen.md files are not hand-edited and .suggest.md are not stale."""
    errors = []

    # Check .gen.md files via git diff
    gen_files = list(WIKI_ROOT.rglob("*.gen.md"))
    if gen_files:
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "--"] + [str(f) for f in gen_files],
                capture_output=True,
                text=True,
                cwd=REPO_ROOT,
            )
            dirty = [l for l in result.stdout.strip().split("\n") if l]
            if dirty:
                for f in dirty:
                    errors.append(f"DIRTY .gen.md (run `make wiki-sync`): {f}")
        except FileNotFoundError:
            pass  # no git

    # Check stale .suggest.md (>30 days)
    suggest_files = list(WIKI_ROOT.rglob("*.suggest.md"))
    now = datetime.now().timestamp()
    for sf in suggest_files:
        age_days = (now - sf.stat().st_mtime) / 86400
        if age_days > 30:
            errors.append(f"STALE .suggest.md ({int(age_days)} days): {sf.relative_to(REPO_ROOT)}")

    if errors:
        for e in errors:
            print(f"  ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    else:
        print("  wiki-lint: all checks passed")


# ---------------------------------------------------------------------------
# suggest subcommand
# ---------------------------------------------------------------------------


def cmd_suggest() -> None:
    """Generate .suggest.md files with agent-proposed content for human review."""
    projects = discover_projects()

    for name in projects:
        proj_dir = WIKI_ROOT / "projects" / name
        suggest_file = proj_dir / "hypotheses.suggest.md"

        # Only create if no existing suggestions and hypotheses.md exists
        hyp_file = proj_dir / "hypotheses.md"
        if suggest_file.exists() or not hyp_file.exists():
            continue

        # Read current hypotheses to see if there are any
        content = hyp_file.read_text()
        if "## H" in content:
            continue  # already has hypotheses, skip

        # Generate a placeholder suggestion
        lines = [
            f"# Suggested Hypotheses for {name}",
            "",
            "> Agent-generated suggestions. Review and promote to `hypotheses.md` or delete this file.",
            "",
            "## H1: [Suggested hypothesis]",
            "",
            "**Status:** #hypothesis/proposed",
            "**Question:** [What biological question could this project address?]",
            "**Approach:** [Suggested analytical approach]",
            "",
        ]
        suggest_file.write_text("\n".join(lines))
        print(f"  wrote {suggest_file}")

    print("\nwiki-suggest complete")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in ("sync", "lint", "suggest"):
        print("Usage: python scripts/sync_wiki.py {sync|lint|suggest}", file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "sync":
        cmd_sync()
    elif cmd == "lint":
        cmd_lint()
    elif cmd == "suggest":
        cmd_suggest()


if __name__ == "__main__":
    main()
