#!/usr/bin/env python3
"""Sync pipeline metadata into the Obsidian wiki and sentinel-marked doc tables.

One script, one direction: code/DB -> .gen.md files and sentinel tables.

Usage:
    python scripts/sync_wiki.py sync      # generate all .gen.md + update doc tables
    python scripts/sync_wiki.py lint      # check .gen.md not hand-edited, stale .suggest.md

The script reads from:
  - sc_tools.pipeline.STANDARD_PHASES (canonical phase metadata)
  - sc_tools.registry (project_phases table, if available)

And writes to:
  - docs/wiki/sc_tools/phases.gen.md
  - docs/wiki/sc_tools/checkpoints.gen.md
  - docs/wiki/sc_tools/changelog.gen.md
  - docs/wiki/projects/{name}/status.gen.md  (per project)
  - README.md, CLAUDE.md, Architecture.md (sentinel-marked tables)
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Repo root is two levels up from scripts/
REPO_ROOT = Path(__file__).resolve().parent.parent
WIKI_ROOT = REPO_ROOT / "docs" / "wiki"


# ---------------------------------------------------------------------------
# Phase table generation from pipeline.py
# ---------------------------------------------------------------------------

def _get_phases() -> dict:
    """Import STANDARD_PHASES from sc_tools.pipeline."""
    sys.path.insert(0, str(REPO_ROOT))
    from sc_tools.pipeline import STANDARD_PHASES
    return STANDARD_PHASES


def generate_phases_md(phases: dict) -> str:
    """Generate docs/wiki/sc_tools/phases.gen.md from PhaseSpec data."""
    fm = _frontmatter({
        "type": "phases",
        "tier": "tool-design",
        "cssclasses": ["generated"],
        "generated": True,
    })
    lines = [
        fm,
        "",
        "# Pipeline Phases",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: `sc_tools/pipeline.py`. Do not edit manually.",
        "",
        "| Slug | Name | Old Code | Branch | Checkpoint | Optional | HIL | Iterative |",
        "|------|------|----------|--------|------------|----------|-----|-----------|",
    ]
    for slug, spec in phases.items():
        cp = f"`{spec.checkpoint}`" if spec.checkpoint else "-"
        opt = "yes" if spec.optional else ""
        hil = "yes" if spec.human_in_loop else ""
        it = "yes" if spec.iterative else ""
        lines.append(
            f"| `{slug}` | {spec.label} | {spec.old_code} | {spec.branch} | {cp} | {opt} | {hil} | {it} |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_checkpoints_md(phases: dict) -> str:
    """Generate docs/wiki/sc_tools/checkpoints.gen.md with required metadata per phase."""
    fm = _frontmatter({
        "type": "checkpoints",
        "tier": "tool-design",
        "cssclasses": ["generated"],
        "generated": True,
    })
    lines = [
        fm,
        "",
        "# Checkpoint Contracts",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: `sc_tools/pipeline.py`. Do not edit manually.",
        "",
    ]
    for slug, spec in phases.items():
        cp = f"`{spec.checkpoint}`" if spec.checkpoint else "*(no checkpoint)*"
        lines.append(f"## {slug}")
        lines.append("")
        lines.append(f"**Label:** {spec.label}  ")
        lines.append(f"**Checkpoint:** {cp}  ")
        if spec.required_obs:
            obs_str = ", ".join(f"`{o}`" for o in spec.required_obs)
            lines.append(f"**Required obs:** {obs_str}  ")
        if spec.required_obsm:
            obsm_str = ", ".join(f"`{o}`" for o in spec.required_obsm)
            lines.append(f"**Required obsm:** {obsm_str}  ")
        if spec.x_format:
            lines.append(f"**X format:** {spec.x_format}  ")
        if spec.qc_report:
            lines.append(f"**QC report:** `{spec.qc_report}`  ")
        lines.append("")
    return "\n".join(lines)


def _frontmatter(props: dict) -> str:
    """Build YAML frontmatter block from a dict of properties."""
    lines = ["---"]
    for k, v in props.items():
        if isinstance(v, list):
            lines.append(f"{k}:")
            for item in v:
                lines.append(f"  - {item}")
        elif isinstance(v, bool):
            lines.append(f"{k}: {'true' if v else 'false'}")
        else:
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines)


def generate_changelog_md() -> str:
    """Generate docs/wiki/sc_tools/changelog.gen.md from registry phase transitions."""
    fm = _frontmatter({
        "type": "changelog",
        "tier": "tool-design",
        "cssclasses": ["generated"],
        "generated": True,
    })
    lines = [
        fm,
        "",
        "# Phase Changelog",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: registry database. Do not edit manually.",
        "",
    ]
    try:
        from sc_tools.registry import Registry
        reg = Registry()
        # Collect all phases across all projects, sort by updated_at desc
        all_entries: list[tuple[str, dict]] = []
        for proj in reg.list_projects():
            proj_name = proj["name"]
            for phase in reg.list_phases(proj_name):
                all_entries.append((proj_name, phase))
        all_entries.sort(key=lambda x: x[1].get("updated_at", ""), reverse=True)
        entries = all_entries[:50]
        if entries:
            lines.append("| Date | Project | Phase | Status |")
            lines.append("|------|---------|-------|--------|")
            for proj_name, phase in entries:
                date_str = str(phase.get("updated_at", ""))[:10] or "?"
                lines.append(
                    f"| {date_str} | {proj_name} | `{phase['phase']}` | {phase['status']} |"
                )
        else:
            lines.append("*No phase transitions recorded yet.*")
    except Exception:
        lines.append("*Registry not available. Run `pip install sc-tools[registry]` to enable.*")
    lines.append("")
    return "\n".join(lines)


def generate_project_status_md(project_name: str) -> str:
    """Generate docs/wiki/projects/{name}/status.gen.md from registry."""
    # Collect phase data for frontmatter
    fm_props: dict = {
        "type": "status",
        "project": project_name,
        "tier": "project",
        "cssclasses": ["generated"],
        "generated": True,
    }

    phases_data: list[dict] = []
    try:
        from sc_tools.registry import Registry
        reg = Registry()
        phases_data = reg.list_phases(project_name)

        # Compute summary stats for frontmatter
        if phases_data:
            complete = sum(1 for p in phases_data if p["status"] == "complete")
            total = len(phases_data)
            fm_props["phases_complete"] = complete
            fm_props["phases_total"] = total

            # Find the furthest active phase
            in_progress = [p for p in phases_data if p["status"] == "in_progress"]
            if in_progress:
                fm_props["current_phase"] = in_progress[-1]["phase"]
            elif complete > 0:
                fm_props["current_phase"] = phases_data[-1]["phase"]

        # Try to get platform from project record
        try:
            proj = reg.get_project(project_name)
            if proj and proj.get("imaging_modality"):
                fm_props["platform"] = proj["imaging_modality"]
        except Exception:
            pass
    except Exception:
        pass

    fm = _frontmatter(fm_props)
    lines = [
        fm,
        "",
        f"# {project_name} — Pipeline Status",
        "",
        "> [!generated] Auto-generated by `make wiki-sync`",
        "> Source: registry database. Do not edit manually.",
        "",
    ]

    if phases_data:
        lines.append("| Phase | Status | n_obs | n_vars | n_samples | Updated | Notes |")
        lines.append("|-------|--------|-------|--------|-----------|---------|-------|")
        for p in phases_data:
            date_str = str(p.get("updated_at", ""))[:10] or ""
            notes = p.get("notes") or ""
            n_obs = f"{p['n_obs']:,}" if p.get("n_obs") else ""
            n_vars = f"{p['n_vars']:,}" if p.get("n_vars") else ""
            n_samples = str(p["n_samples"]) if p.get("n_samples") else ""
            lines.append(
                f"| `{p['phase']}` | {p['status']} | {n_obs} | {n_vars} | {n_samples} | {date_str} | {notes} |"
            )
    else:
        lines.append("*No phase data recorded. Use `set_phase_status` MCP tool or registry API.*")

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Sentinel table replacement in doc files
# ---------------------------------------------------------------------------

def _build_phase_table(phases: dict) -> str:
    """Build the markdown phase table used in README, CLAUDE.md, Architecture.md."""
    lines = [
        "| Slug | Old code | Name | Checkpoint | Required Data | QC Report |",
        "|------|----------|------|------------|---------------|-----------|",
    ]
    for slug, spec in phases.items():
        cp = f"`{spec.checkpoint}`" if spec.checkpoint else "-"
        # Build required data summary
        parts = []
        if spec.required_obs:
            parts.append(f"`obs[{', '.join(spec.required_obs)}]`")
        if spec.required_obsm:
            parts.append(f"`obsm[{', '.join(spec.required_obsm)}]`")
        if spec.x_format:
            parts.append(f"`X` {spec.x_format}")
        req = ", ".join(parts) if parts else "-"
        qc = f"`{spec.qc_report}`" if spec.qc_report else ""
        lines.append(
            f"| `{slug}` | {spec.old_code} | {spec.label} | {cp} | {req} | {qc} |"
        )
    return "\n".join(lines)


SENTINEL_PATTERN = re.compile(
    r"(<!-- PHASE_TABLE:START -->)\n.*?\n(<!-- PHASE_TABLE:END -->)",
    re.DOTALL,
)

PROJECT_TABLE_PATTERN = re.compile(
    r"(<!-- PROJECT_TABLE:START -->)\n.*?\n(<!-- PROJECT_TABLE:END -->)",
    re.DOTALL,
)


def update_sentinel_file(filepath: Path, table: str) -> bool:
    """Replace content between PHASE_TABLE sentinels. Returns True if changed."""
    if not filepath.exists():
        return False
    content = filepath.read_text()
    if "<!-- PHASE_TABLE:START -->" not in content:
        return False
    replacement = f"<!-- PHASE_TABLE:START -->\n{table}\n<!-- PHASE_TABLE:END -->"
    new_content = SENTINEL_PATTERN.sub(replacement, content)
    if new_content == content:
        return False
    filepath.write_text(new_content)
    return True


_PLATFORM_LABELS: dict[str, str] = {
    "sequencing_based": "Visium",
    "mass_spec_imaging": "IMC",
    "probe_based": "CosMx",
    "multiplatform": "Multi",
}

# Projects with wiki pages (have Mission.md, Journal.md, hypotheses.md links)
_WIKI_PROJECTS: dict[str, str] = {
    "ggo_visium": "[[ggo_visium/Mission\\|Mission]] · [[ggo_visium/hypotheses\\|Hyp]] · [[ggo_visium/Journal\\|Journal]]",
    "robin": "[[robin/Mission\\|Mission]] · [[robin/hypotheses\\|Hyp]] · [[robin/Journal\\|Journal]]",
    "lymph_dlbcl": "[[lymph_dlbcl/Mission\\|Mission]] · [[lymph_dlbcl/hypotheses\\|Hyp]] · [[lymph_dlbcl/Journal\\|Journal]]",
    "ggo_human": "[[ggo_human/hypotheses\\|Hyp]] · [[ggo_human/journal\\|Journal]]",
    "ibd_spatial": "[[ibd_spatial/Mission\\|Mission]] · [[ibd_spatial/hypotheses\\|Hyp]] · [[ibd_spatial/Journal\\|Journal]]",
    "robin_cell": "[[robin/Mission\\|Mission]]",
}


def _build_project_table() -> str:
    """Build a markdown project summary table from registry data.

    Wiki projects (those with Mission/Journal/hypotheses pages) go in the main
    table with links.  Extra registry-only projects are listed in a collapsed
    details block underneath.
    """
    def _friendly_platform(proj: dict) -> str:
        raw = proj.get("imaging_modality") or proj.get("domain") or ""
        return _PLATFORM_LABELS.get(raw, raw)

    def _phase_summary(phases: list[dict]) -> tuple[str, str, str, str, str]:
        complete = sum(1 for p in phases if p["status"] == "complete")
        total = len(phases)
        progress = f"{complete}/{total}" if total else "0/0"
        current = ""
        in_prog = [p for p in phases if p["status"] == "in_progress"]
        if in_prog:
            current = in_prog[-1]["phase"]
        elif phases:
            done = [p for p in phases if p["status"] == "complete"]
            if done:
                current = done[-1]["phase"]
        n_obs = n_vars = n_samples = ""
        for p in reversed(phases):
            if p.get("n_obs"):
                n_obs = f"{p['n_obs']:,}"
                break
        for p in reversed(phases):
            if p.get("n_vars"):
                n_vars = f"{p['n_vars']:,}"
                break
        for p in reversed(phases):
            if p.get("n_samples"):
                n_samples = str(p["n_samples"])
                break
        return current, n_obs, n_vars, n_samples, progress

    main_lines = [
        "| Project | Platform | Current Phase | n_obs | n_vars | Progress | Links |",
        "|---------|----------|---------------|-------|--------|----------|-------|",
    ]
    extra_lines = [
        "| Project | Platform | Current Phase | Progress |",
        "|---------|----------|---------------|----------|",
    ]
    try:
        from sc_tools.registry import Registry
        reg = Registry()
        for proj in reg.list_projects():
            name = proj["name"]
            platform = _friendly_platform(proj)
            phases = reg.list_phases(name)
            current, n_obs, n_vars, n_samples, progress = _phase_summary(phases)

            if name in _WIKI_PROJECTS:
                links = _WIKI_PROJECTS[name]
                main_lines.append(
                    f"| **{name}** | {platform} | {current} | {n_obs} | {n_vars} | {progress} | {links} |"
                )
            else:
                extra_lines.append(
                    f"| {name} | {platform} | {current} | {progress} |"
                )
    except Exception:
        main_lines.append("| *(registry unavailable)* | | | | | | |")

    parts = ["\n".join(main_lines)]
    if len(extra_lines) > 2:  # more than just header + separator
        parts.append("")
        parts.append("<details><summary>Registry-only projects (no wiki pages)</summary>")
        parts.append("")
        parts.append("\n".join(extra_lines))
        parts.append("")
        parts.append("</details>")
    return "\n".join(parts)


def update_project_table_file(filepath: Path, table: str) -> bool:
    """Replace content between PROJECT_TABLE sentinels. Returns True if changed."""
    if not filepath.exists():
        return False
    content = filepath.read_text()
    if "<!-- PROJECT_TABLE:START -->" not in content:
        return False
    replacement = f"<!-- PROJECT_TABLE:START -->\n{table}\n<!-- PROJECT_TABLE:END -->"
    new_content = PROJECT_TABLE_PATTERN.sub(replacement, content)
    if new_content == content:
        return False
    filepath.write_text(new_content)
    return True


# ---------------------------------------------------------------------------
# Discover projects
# ---------------------------------------------------------------------------

def discover_projects() -> list[str]:
    """Find project names from docs/wiki/projects/ or projects/ directory."""
    wiki_projects = WIKI_ROOT / "projects"
    if wiki_projects.exists():
        return [
            d.name for d in sorted(wiki_projects.iterdir())
            if d.is_dir() and not d.name.startswith(".")
        ]
    # Fallback: scan projects/ for directories with Mission.md or Journal.md
    projects_root = REPO_ROOT / "projects"
    names = []
    for platform_dir in sorted(projects_root.iterdir()):
        if not platform_dir.is_dir() or platform_dir.name.startswith("."):
            continue
        for proj_dir in sorted(platform_dir.iterdir()):
            if proj_dir.is_dir() and (
                (proj_dir / "Journal.md").exists()
                or (proj_dir / "Snakefile").exists()
            ):
                names.append(proj_dir.name)
    return names


# ---------------------------------------------------------------------------
# sync subcommand
# ---------------------------------------------------------------------------

def cmd_sync() -> None:
    """Generate all .gen.md files and update sentinel tables."""
    phases = _get_phases()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    # 1. Wiki .gen.md files
    sc_dir = WIKI_ROOT / "sc_tools"
    sc_dir.mkdir(parents=True, exist_ok=True)

    (sc_dir / "phases.gen.md").write_text(generate_phases_md(phases))
    print(f"  wrote {sc_dir / 'phases.gen.md'}")

    (sc_dir / "checkpoints.gen.md").write_text(generate_checkpoints_md(phases))
    print(f"  wrote {sc_dir / 'checkpoints.gen.md'}")

    (sc_dir / "changelog.gen.md").write_text(generate_changelog_md())
    print(f"  wrote {sc_dir / 'changelog.gen.md'}")

    # 2. Per-project status.gen.md
    projects = discover_projects()
    for name in projects:
        proj_dir = WIKI_ROOT / "projects" / name
        proj_dir.mkdir(parents=True, exist_ok=True)
        (proj_dir / "status.gen.md").write_text(generate_project_status_md(name))
        print(f"  wrote {proj_dir / 'status.gen.md'}")

    # 3. Sentinel tables in doc files
    table = _build_phase_table(phases)
    for doc in ["README.md", "CLAUDE.md", "Architecture.md"]:
        filepath = REPO_ROOT / doc
        if update_sentinel_file(filepath, table):
            print(f"  updated sentinel in {doc}")
        else:
            if filepath.exists() and "<!-- PHASE_TABLE:START -->" not in filepath.read_text():
                print(f"  skip {doc} (no sentinels yet)")

    # 4. Project table in index.md
    project_table = _build_project_table()
    index_path = WIKI_ROOT / "index.md"
    if update_project_table_file(index_path, project_table):
        print(f"  updated PROJECT_TABLE in index.md")

    print(f"\nwiki-sync complete at {now}")


# ---------------------------------------------------------------------------
# lint subcommand
# ---------------------------------------------------------------------------

def cmd_lint() -> None:
    """Check .gen.md files are not hand-edited and .suggest.md are not stale."""
    errors = []

    # Check .gen.md files via git diff
    gen_files = list(WIKI_ROOT.rglob("*.gen.md"))
    if gen_files:
        try:
            result = subprocess.run(
                ["git", "diff", "--name-only", "--"] + [str(f) for f in gen_files],
                capture_output=True, text=True, cwd=REPO_ROOT,
            )
            dirty = [l for l in result.stdout.strip().split("\n") if l]
            if dirty:
                for f in dirty:
                    errors.append(f"DIRTY .gen.md (run `make wiki-sync`): {f}")
        except FileNotFoundError:
            pass  # no git

    # Check stale .suggest.md (>30 days)
    suggest_files = list(WIKI_ROOT.rglob("*.suggest.md"))
    now = datetime.now().timestamp()
    for sf in suggest_files:
        age_days = (now - sf.stat().st_mtime) / 86400
        if age_days > 30:
            errors.append(f"STALE .suggest.md ({int(age_days)} days): {sf.relative_to(REPO_ROOT)}")

    if errors:
        for e in errors:
            print(f"  ERROR: {e}", file=sys.stderr)
        sys.exit(1)
    else:
        print("  wiki-lint: all checks passed")


# ---------------------------------------------------------------------------
# suggest subcommand
# ---------------------------------------------------------------------------

def cmd_suggest() -> None:
    """Generate .suggest.md files with agent-proposed content for human review."""
    projects = discover_projects()

    for name in projects:
        proj_dir = WIKI_ROOT / "projects" / name
        suggest_file = proj_dir / "hypotheses.suggest.md"

        # Only create if no existing suggestions and hypotheses.md exists
        hyp_file = proj_dir / "hypotheses.md"
        if suggest_file.exists() or not hyp_file.exists():
            continue

        # Read current hypotheses to see if there are any
        content = hyp_file.read_text()
        if "## H" in content:
            continue  # already has hypotheses, skip

        # Generate a placeholder suggestion
        lines = [
            f"# Suggested Hypotheses for {name}",
            "",
            "> Agent-generated suggestions. Review and promote to `hypotheses.md` or delete this file.",
            "",
            "## H1: [Suggested hypothesis]",
            "",
            "**Status:** #hypothesis/proposed",
            "**Question:** [What biological question could this project address?]",
            "**Approach:** [Suggested analytical approach]",
            "",
        ]
        suggest_file.write_text("\n".join(lines))
        print(f"  wrote {suggest_file}")

    print("\nwiki-suggest complete")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] not in ("sync", "lint", "suggest"):
        print("Usage: python scripts/sync_wiki.py {sync|lint|suggest}", file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "sync":
        cmd_sync()
    elif cmd == "lint":
        cmd_lint()
    elif cmd == "suggest":
        cmd_suggest()


if __name__ == "__main__":
    main()
